// Acá se agrega la configuración de las tarjetas, si se necesita agregar o quitar datos, hacerlo aquí
export const CARDS_CONFIG = [
    // *! No poner la tarjeta de ubicación, se maneja aparte
    {
        id: "popup-fecha", // ID único para cada tarjeta
        className: "cs", // Clase CSS para el color del logo
        icon: "schedule", // Icono de Material Symbols
        title: "Última Actualización", // Título de la tarjeta
        dataKey: "Fecha", // Clave en los datos para obtener el valor del json
        color: null, // Color para el gráfico (no se usa en esta tarjeta)
        showChart: false, // Indica si se muestra el gráfico al hacer clic
        unit: '', // Unidad de medida (no se usa en esta tarjeta)
    },
    {
        id: "popup-voltaje",
        className: "mth",
        icon: "battery_5_bar",
        title: "Voltaje de la batería",
        dataKey: "Nivel de bateria",
        color: "255, 99, 132",
        showChart: true,
        unit: "V",
    },
    {
        id: "popup-temperatura",
        className: "qw",
        icon: "device_thermostat",
        title: "Temperatura",
        dataKey: "Temperatura Promedio",
        color: "79, 126, 255",
        showChart: true,
        unit: "°C",
    },
    {
        id: "popup-stermica",
        className: "mth",
        icon: "nest_thermostat_zirconium_eu",
        title: "Sensación Térmica",
        dataKey: "Sensacion T",
        color: "0, 255, 255",
        showChart: true,
        unit: "°C",
    },
    {
        id: "popup-bp",
        className: "cs",
        icon: "cloud",
        title: "Presión Atmosférica",
        dataKey: "Presion",
        color: "153, 102, 255",
        showChart: true,
        unit: "hPa",
    },
    {
        id: "popup-hum",
        className: "eg",
        icon: "water_drop",
        title: "Humedad Relativa",
        dataKey: "Humedad",
        color: "255, 159, 64",
        showChart: true,
        unit: "%",
    },
    {
        id: "popup-altitud",
        className: "cs",
        icon: "altitude",
        title: "Altitud",
        dataKey: "Altitud",
        color: "102, 255, 102",
        showChart: true,
        unit: "m",
    },
    {
        id: "popup-luz",
        className: "qw",
        icon: "light_mode",
        title: "Nivel de luz",
        dataKey: "Nivel de luz",
        color: "255, 205, 86",
        showChart: true,
        unit: "lm",
    },
    {
        id: "popup-rocio",
        className: "cs",
        icon: "dew_point",
        title: "Punto de rocío",
        dataKey: "Temperatura punto de rocio",
        color: "255, 51, 153",
        showChart: true,
        unit: "°C",
    },
    {
        id: "popup-co2",
        className: "mth",
        icon: "eco",
        title: "Partes por millón CO2",
        dataKey: "ppm CO2",
        color: "204, 204, 0",
        showChart: true,
        unit: "KΩ",
    },
    {
        id: "popup-aire",
        className: "eg",
        icon: "air",
        title: "Calidad del aire",
        dataKey: "Calidad del aire",
        color: "54, 162, 235",
        showChart: true,
        unit: '',
    },
    {
        id: "popup-vientoVel",
        className: "qw",
        icon: "wind_power",
        title: "Velocidad del viento",
        dataKey: "Velocidad del viento",
        color: "0, 204, 255",
        showChart: true,
        unit: '',
    },
    {
        id: "popup-vientoDir",
        className: "eg",
        icon: "read_more",
        title: "Dirección del viento",
        dataKey: "Direccion del viento",
        color: "153, 255, 255",
        showChart: true,
        unit: '',
    },
    {
        id: "popup-lluvia",
        className: "qw",
        icon: "rainy",
        title: "Sensor de lluvia",
        dataKey: "Sensor de lluvia",
        color: "179, 179, 255",
        showChart: true,
        unit: '',
    },
];
